# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from runmesh.v1 import worker_pb2 as runmesh_dot_v1_dot_worker__pb2


class WorkerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lease = channel.unary_unary(
                '/runmesh.v1.WorkerService/Lease',
                request_serializer=runmesh_dot_v1_dot_worker__pb2.LeaseRequest.SerializeToString,
                response_deserializer=runmesh_dot_v1_dot_worker__pb2.LeaseResponse.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/runmesh.v1.WorkerService/Start',
                request_serializer=runmesh_dot_v1_dot_worker__pb2.StartRequest.SerializeToString,
                response_deserializer=runmesh_dot_v1_dot_worker__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/runmesh.v1.WorkerService/Heartbeat',
                request_serializer=runmesh_dot_v1_dot_worker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=runmesh_dot_v1_dot_worker__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Complete = channel.unary_unary(
                '/runmesh.v1.WorkerService/Complete',
                request_serializer=runmesh_dot_v1_dot_worker__pb2.CompleteRequest.SerializeToString,
                response_deserializer=runmesh_dot_v1_dot_worker__pb2.CompleteResponse.FromString,
                _registered_method=True)
        self.Fail = channel.unary_unary(
                '/runmesh.v1.WorkerService/Fail',
                request_serializer=runmesh_dot_v1_dot_worker__pb2.FailRequest.SerializeToString,
                response_deserializer=runmesh_dot_v1_dot_worker__pb2.FailResponse.FromString,
                _registered_method=True)
        self.CreateArtifactUpload = channel.unary_unary(
                '/runmesh.v1.WorkerService/CreateArtifactUpload',
                request_serializer=runmesh_dot_v1_dot_worker__pb2.CreateArtifactUploadRequest.SerializeToString,
                response_deserializer=runmesh_dot_v1_dot_worker__pb2.CreateArtifactUploadResponse.FromString,
                _registered_method=True)
        self.CompleteArtifactUpload = channel.unary_unary(
                '/runmesh.v1.WorkerService/CompleteArtifactUpload',
                request_serializer=runmesh_dot_v1_dot_worker__pb2.CompleteArtifactUploadRequest.SerializeToString,
                response_deserializer=runmesh_dot_v1_dot_worker__pb2.CompleteArtifactUploadResponse.FromString,
                _registered_method=True)
        self.GetArtifactDownload = channel.unary_unary(
                '/runmesh.v1.WorkerService/GetArtifactDownload',
                request_serializer=runmesh_dot_v1_dot_worker__pb2.GetArtifactDownloadRequest.SerializeToString,
                response_deserializer=runmesh_dot_v1_dot_worker__pb2.GetArtifactDownloadResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Lease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateArtifactUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteArtifactUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifactDownload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lease': grpc.unary_unary_rpc_method_handler(
                    servicer.Lease,
                    request_deserializer=runmesh_dot_v1_dot_worker__pb2.LeaseRequest.FromString,
                    response_serializer=runmesh_dot_v1_dot_worker__pb2.LeaseResponse.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=runmesh_dot_v1_dot_worker__pb2.StartRequest.FromString,
                    response_serializer=runmesh_dot_v1_dot_worker__pb2.StartResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=runmesh_dot_v1_dot_worker__pb2.HeartbeatRequest.FromString,
                    response_serializer=runmesh_dot_v1_dot_worker__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=runmesh_dot_v1_dot_worker__pb2.CompleteRequest.FromString,
                    response_serializer=runmesh_dot_v1_dot_worker__pb2.CompleteResponse.SerializeToString,
            ),
            'Fail': grpc.unary_unary_rpc_method_handler(
                    servicer.Fail,
                    request_deserializer=runmesh_dot_v1_dot_worker__pb2.FailRequest.FromString,
                    response_serializer=runmesh_dot_v1_dot_worker__pb2.FailResponse.SerializeToString,
            ),
            'CreateArtifactUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateArtifactUpload,
                    request_deserializer=runmesh_dot_v1_dot_worker__pb2.CreateArtifactUploadRequest.FromString,
                    response_serializer=runmesh_dot_v1_dot_worker__pb2.CreateArtifactUploadResponse.SerializeToString,
            ),
            'CompleteArtifactUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteArtifactUpload,
                    request_deserializer=runmesh_dot_v1_dot_worker__pb2.CompleteArtifactUploadRequest.FromString,
                    response_serializer=runmesh_dot_v1_dot_worker__pb2.CompleteArtifactUploadResponse.SerializeToString,
            ),
            'GetArtifactDownload': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifactDownload,
                    request_deserializer=runmesh_dot_v1_dot_worker__pb2.GetArtifactDownloadRequest.FromString,
                    response_serializer=runmesh_dot_v1_dot_worker__pb2.GetArtifactDownloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runmesh.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runmesh.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Lease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runmesh.v1.WorkerService/Lease',
            runmesh_dot_v1_dot_worker__pb2.LeaseRequest.SerializeToString,
            runmesh_dot_v1_dot_worker__pb2.LeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runmesh.v1.WorkerService/Start',
            runmesh_dot_v1_dot_worker__pb2.StartRequest.SerializeToString,
            runmesh_dot_v1_dot_worker__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runmesh.v1.WorkerService/Heartbeat',
            runmesh_dot_v1_dot_worker__pb2.HeartbeatRequest.SerializeToString,
            runmesh_dot_v1_dot_worker__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runmesh.v1.WorkerService/Complete',
            runmesh_dot_v1_dot_worker__pb2.CompleteRequest.SerializeToString,
            runmesh_dot_v1_dot_worker__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runmesh.v1.WorkerService/Fail',
            runmesh_dot_v1_dot_worker__pb2.FailRequest.SerializeToString,
            runmesh_dot_v1_dot_worker__pb2.FailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateArtifactUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runmesh.v1.WorkerService/CreateArtifactUpload',
            runmesh_dot_v1_dot_worker__pb2.CreateArtifactUploadRequest.SerializeToString,
            runmesh_dot_v1_dot_worker__pb2.CreateArtifactUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteArtifactUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runmesh.v1.WorkerService/CompleteArtifactUpload',
            runmesh_dot_v1_dot_worker__pb2.CompleteArtifactUploadRequest.SerializeToString,
            runmesh_dot_v1_dot_worker__pb2.CompleteArtifactUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifactDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runmesh.v1.WorkerService/GetArtifactDownload',
            runmesh_dot_v1_dot_worker__pb2.GetArtifactDownloadRequest.SerializeToString,
            runmesh_dot_v1_dot_worker__pb2.GetArtifactDownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
